export const ENV = {
  // environment variables
  NEXT_PUBLIC_WEBSITE_URL: process.env.NEXT_PUBLIC_WEBSITE_URL || 'http://localhost:3000',
  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || 'xxxx',
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  AUTH_SECRET: process.env.AUTH_SECRET || 'xxxx',
  NODE_ENV: process.env.NODE_ENV || 'development',

  // Wakatime API URLs
  WAKATIME_WEEKLY_CODING_ACTIVITY_URL: process.env.WAKATIME_WEEKLY_CODING_ACTIVITY_URL || 'default_url',
  WAKATIME_WEEKLY_CODING_LANGUAGES_URL: process.env.WAKATIME_WEEKLY_CODING_LANGUAGES_URL || 'default_url',
}